spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          #唯一标识符
        - id: changgou_goods_route
          #用户请求后路由到该服务[微服务]
          #uri: http://localhost:18081
          #使用LoadBalancerClient实现负载均衡，路由到http://localhost:18081微服务
          uri: lb://goods
          #路由断言，路由规则配置
          predicates:
          #用户请求的域名规则配置
          #- Host=cloud.itheima.com**
          - Path=/api/brand**
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的factory
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 4
        #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
          - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
          - StripPrefix=1
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true